/*
This file is part of PPTRemote_Server v0.1

PPTRemote_Server is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PPTRemote_Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with PPTRemote_Server.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.deepak.pptrserver.gui;

import com.deepak.pptrserver.core.bluetooth.BluetoothCommunicator;
import com.deepak.pptrserver.core.bluetooth.BluetoothMessage;
import com.deepak.pptrserver.core.bluetooth.BluetoothReader;
import com.deepak.pptrserver.core.bluetooth.BluetoothUI;
import com.deepak.pptrserver.core.command.PPTCommand;
import com.deepak.pptrserver.core.controller.Remote;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author deepak
 */

/*
 * this class impliments the UI for the project
 * since this class uses the bluetooth communicator for server services
 * the class impliments the bluetooth UI interface and defines the
 * connection established method.
 */
public class MainWindow extends javax.swing.JFrame implements PropertyChangeListener, BluetoothUI {

    // the universal unique identifier for the server service
    private String serviceUUID = "27012f0c68af4fbf8dbe6bbaf7aa432a";
    // server name
    private String serverName = "btserver";
    // the bluetooth communicator object for bluetooth connections
    private BluetoothCommunicator bluetoothCommunicator = null;
    // the bluetooth reader object for reading from the string
    private BluetoothReader bluetoothReader = null;
    // bluetooth message object
    private BluetoothMessage bluetoothMessage = null;
    // remote controller object
    private Remote remote = null;
    // the recieved message
    private int recievedMsg = 0;
    // the connection state
    private boolean isConnected = false;
    // the label images
    private ImageIcon commandBase = null;
    private ImageIcon commandNext = null;
    private ImageIcon commandPrevious = null;
    private ImageIcon connectBase = null;
    private ImageIcon connectMouseOver = null;
    private ImageIcon connectSelected = null;
    // the label icon changer object
    private LabelIconChanger labelIconChanger = null;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        // set the frame icon
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/com/deepak/pptrserver/resources/logo_16x16.png")));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        // initialise the remote object
        remote = new Remote();
        // intialise the icon images
        commandBase = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/command_base.png"));
        commandNext = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/command_next.png"));
        commandPrevious = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/command_previous.png"));
        connectBase = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/connect_base.png"));
        connectMouseOver = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/connect_mouseOver.png"));
        connectSelected = new ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/connect_selected.png"));
        // initialise the label icon changer object
        labelIconChanger = new LabelIconChanger();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        baseImageLabel = new javax.swing.JLabel();
        connectButton_Label = new javax.swing.JLabel();
        nextIndicator_Label = new javax.swing.JLabel();
        previousIndicator_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PPTR");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingEvent(evt);
            }
        });

        baseImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/base.png"))); // NOI18N
        baseImageLabel.setBounds(0, 0, 165, 200);
        layeredPane.add(baseImageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        connectButton_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/connect_base.png"))); // NOI18N
        connectButton_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connectButton_MouseEnteredEvent(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                connectButton_MouseExittedEvent(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectButton_MousePressedEvent(evt);
            }
        });
        connectButton_Label.setBounds(96, 74, 40, 50);
        layeredPane.add(connectButton_Label, javax.swing.JLayeredPane.POPUP_LAYER);

        nextIndicator_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/command_base.png"))); // NOI18N
        nextIndicator_Label.setBounds(58, 87, 13, 30);
        layeredPane.add(nextIndicator_Label, javax.swing.JLayeredPane.POPUP_LAYER);

        previousIndicator_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/deepak/pptrserver/resources/command_base.png"))); // NOI18N
        previousIndicator_Label.setBounds(40, 87, 13, 30);
        layeredPane.add(previousIndicator_Label, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * method to stop the server service and close the bluetooth connection
     */
    private void closeBluetoothConnection() {
        // first if the reader is present then
        if (bluetoothReader != null) {
            // stop reading
            bluetoothReader.stopReading();
        }
        // if the bluetooth communicator is present and connected
        if (bluetoothCommunicator != null && bluetoothCommunicator.isConnected()) {
            try {
                // stop the service
                bluetoothCommunicator.stopService();
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /*
     * this method is called when the UI window is closed
     */
    private void windowClosingEvent(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingEvent
        // TODO add your handling code here:
        // stop the server service and close the bluetooth connection
        closeBluetoothConnection();
    }//GEN-LAST:event_windowClosingEvent

    private void connectButton_MousePressedEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButton_MousePressedEvent
        // TODO add your handling code here:
        if (!isConnected) {
            // set is connected flag to true
            isConnected = true;
            // change icon to selected
            connectButton_Label.setIcon(connectSelected);
            // initialise the communicator
            bluetoothCommunicator = new BluetoothCommunicator(this);
            // start service with service uuid and server name
            bluetoothCommunicator.startService(serviceUUID, serverName);
            // create a bluetooth message object
            bluetoothMessage = new BluetoothMessage();
            // add the current class as a listner for the message
            bluetoothMessage.addPropertyChangeListener(this);
        } else {
            // set is connected flag to false
            isConnected = false;
            // change icon to base icon
            connectButton_Label.setIcon(connectBase);
            // stop the server service and close the bluetooth connection
            closeBluetoothConnection();
        }
    }//GEN-LAST:event_connectButton_MousePressedEvent

    private void connectButton_MouseEnteredEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButton_MouseEnteredEvent
        // TODO add your handling code here:
        if (!isConnected) {
            connectButton_Label.setIcon(connectMouseOver);
        }
    }//GEN-LAST:event_connectButton_MouseEnteredEvent

    private void connectButton_MouseExittedEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButton_MouseExittedEvent
        // TODO add your handling code here:
        if (!isConnected) {
            connectButton_Label.setIcon(connectBase);
        }
    }//GEN-LAST:event_connectButton_MouseExittedEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baseImageLabel;
    private javax.swing.JLabel connectButton_Label;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel nextIndicator_Label;
    private javax.swing.JLabel previousIndicator_Label;
    // End of variables declaration//GEN-END:variables

    /*
     * this method is called when message is recieved and the bluetooth message content changes
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        // append the recieved message to the frame text area
        recievedMsg = bluetoothMessage.getMessage();
        if (recievedMsg == PPTCommand.NEXT_SLIDE) {
            remote.next();
            labelIconChanger.change(nextIndicator_Label, commandNext, commandBase);
        } else if (recievedMsg == PPTCommand.PREVIOUS_SLIDE) {
            remote.previous();
            labelIconChanger.change(previousIndicator_Label, commandPrevious, commandBase);
        }
    }

    /*
     * the connection established method implimentation for the bluetoothUI interface
     */
    public void connectionEstablished() {
        // create bluetooth reader using the data input stream and bluetooth message as the parameter
        bluetoothReader = new BluetoothReader(bluetoothCommunicator.getDataInputStream(), bluetoothMessage);
        // start reading from the streams using the reader
        bluetoothReader.startReading();
    }
}
